#!/usr/bin/env node
// Assemble the single-file Scope client served by `maco scope serve`.
// The live observer IIFE is copied verbatim so existing HTML contract tests keep matching.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(root, "..");
const outPath = resolve(
  process.argv[2] || join(repoRoot, "src/scope/placeholder.html"),
);
mkdirSync(dirname(outPath), { recursive: true });

const read = (relative) => readFileSync(join(root, relative), "utf8");

const MODULES = [
  {
    file: "src/lifecycle.mjs",
    globalName: "lifecycle",
    names: [
      "DEFAULT_STATUS",
      "normalizedStatus",
      "explicitLifecycleStatus",
      "lifecycleStatus",
      "failedGate",
      "passedGate",
      "gateDetail",
      "gateStatus",
      "statusFromEvent",
      "displayRole",
      "arrayStrings",
      "coverageEvidence",
    ],
  },
  {
    file: "src/api.mjs",
    globalName: "api",
    names: ["fetchProjects", "fetchRunEvents", "streamUrl", "parseProjectsPayload"],
  },
  {
    file: "src/catalog.mjs",
    globalName: "catalog",
    names: ["catalogRows", "catalogSummary", "liveHref"],
  },
  {
    file: "src/objective.mjs",
    globalName: "objective",
    names: [
      "DEFAULT_OBJECTIVE",
      "cloneObjective",
      "qualityWeightSum",
      "axisWeightSum",
      "validateObjective",
      "meanValue",
      "rescoreQualityComponents",
      "extractRunQuality",
      "summarizeFromRuns",
      "summarizeFromProfileSummaries",
      "loadEvaluationDocument",
      "rescoreLoaded",
      "rescoreFromRuns",
      "rescoreRow",
      "dominatesCostQuality",
      "paretoFrontier",
      "selectProfile",
    ],
  },
  {
    file: "src/router.mjs",
    globalName: "router",
    names: ["PAGES", "parseHash", "hrefFor", "pageFromLocation"],
  },
];

const legacy = read("src/live/legacy.html");
const styleMatch = legacy.match(/<style>([\s\S]*?)<\/style>/);
const bodyMatch = legacy.match(/<body[^>]*>([\s\S]*)<\/body>/);
if (!styleMatch || !bodyMatch) {
  throw new Error("legacy live HTML is missing <style> or <body>");
}

const liveScriptMatch = bodyMatch[1].match(/<script>([\s\S]*?)<\/script>/);
if (!liveScriptMatch) {
  throw new Error("legacy live HTML is missing its script block");
}

const liveMarkup = bodyMatch[1].replace(/<script>[\s\S]*?<\/script>/, "").trim();
const liveStyle = styleMatch[1];
const liveScript = liveScriptMatch[1];

function wrapModule(source, globalName, names) {
  const stripped = source
    .replace(/^import .+?;\n/gm, "")
    .replace(/^export /gm, "")
    .trim();
  const assigns = names.map((name) => `    ${name}: ${name}`).join(",\n");
  return `(function (global) {
${stripped}
  global.MacoScope = global.MacoScope || {};
  global.MacoScope.${globalName} = {
${assigns}
  };
})(globalThis);`;
}

const prelude = MODULES.map((entry) =>
  wrapModule(read(entry.file), entry.globalName, entry.names),
).join("\n");

function stripLegacyChrome(markup) {
  return markup
    .replace(/<main class="shell">/, "")
    .replace(/<header class="masthead">[\s\S]*?<\/header>/, "")
    .replace(/<footer class="statusbar">[\s\S]*?<\/footer>/, "")
    .replace(/<\/main>/, "")
    .trim();
}

const nav = `      <nav id="appNav" class="app-nav" aria-label="Scope client pages">
        <a href="#/live" data-page="live">Live</a>
        <a href="#/catalog" data-page="catalog">Catalog</a>
        <a href="#/objective" data-page="objective">Objective</a>
      </nav>`;

const documentHtml = `<!doctype html>
<!-- Generated by scope-ui/scripts/build.mjs. Edit sources under scope-ui/. -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MACO Scope</title>
    <style>
${liveStyle}
${read("src/views/app.css")}
    </style>
  </head>
  <body data-maco-scope-ui="client-v1">
    <!-- Stable marker: MACO_SCOPE_LIVE_MULTIPROJECT_UI -->
    <main class="shell">
      <header class="masthead">
        <h1 class="brand"><span>MACO</span> Scope</h1>
        <div id="connection" class="connection" data-state="loading" role="status" aria-live="polite">DISCOVERING</div>
      </header>
${nav}
      <div id="liveView" data-maco-scope-ui="live-multiproject-v2">
${stripLegacyChrome(liveMarkup)}
      </div>
${read("src/views/catalog.html")}
${read("src/views/objective.html")}
      <footer class="statusbar">
        <span id="statusMessage">Read-only local observer</span>
        <span id="errorMessage" class="error" role="alert"></span>
      </footer>
    </main>
    <script>
${prelude}
${liveScript}
${read("src/views/app.js")}
${read("src/views/catalog-view.js")}
${read("src/views/objective-view.js")}
    </script>
  </body>
</html>
`;

writeFileSync(outPath, documentHtml);
process.stdout.write("wrote " + outPath + " (" + documentHtml.length + " bytes)\n");
